//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormAccess
    {
        public int Id { get; set; }
        public int FormIdFK { get; set; }
        public Nullable<bool> ReadForm { get; set; }
        public Nullable<bool> createForm { get; set; }
        public Nullable<bool> EditForm { get; set; }
        public Nullable<bool> DeleteForm { get; set; }
        public int RoleidFK { get; set; }
    
        public virtual FormInfo FormInfo { get; set; }
        public virtual Role Role { get; set; }
    }
}
