//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Form.
        /// </summary>
        public static string Ddl_Form {
            get {
                return ResourceManager.GetString("Ddl_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Form.
        /// </summary>
        public static string DDl_Form_error {
            get {
                return ResourceManager.GetString("DDl_Form_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Role.
        /// </summary>
        public static string Ddl_Role {
            get {
                return ResourceManager.GetString("Ddl_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Role.
        /// </summary>
        public static string DDl_Role_error {
            get {
                return ResourceManager.GetString("DDl_Role_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name is Required.
        /// </summary>
        public static string Label_City_Name_Required {
            get {
                return ResourceManager.GetString("Label_City_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required.
        /// </summary>
        public static string Label_City_Required {
            get {
                return ResourceManager.GetString("Label_City_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Label_CityName {
            get {
                return ResourceManager.GetString("Label_CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name is Required.
        /// </summary>
        public static string Label_Country_Name_Required {
            get {
                return ResourceManager.GetString("Label_Country_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is Required.
        /// </summary>
        public static string Label_Country_Required {
            get {
                return ResourceManager.GetString("Label_Country_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countryyyyyy.
        /// </summary>
        public static string Label_CountryName {
            get {
                return ResourceManager.GetString("Label_CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Label_Create {
            get {
                return ResourceManager.GetString("Label_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string Label_DateOfBirth {
            get {
                return ResourceManager.GetString("Label_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Label_Delete {
            get {
                return ResourceManager.GetString("Label_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Label_Edit {
            get {
                return ResourceManager.GetString("Label_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Email.
        /// </summary>
        public static string Label_Email_Employee {
            get {
                return ResourceManager.GetString("Label_Email_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Email is required.
        /// </summary>
        public static string Label_Email_Employee_Required {
            get {
                return ResourceManager.GetString("Label_Email_Employee_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Number.
        /// </summary>
        public static string Label_EmployNumber {
            get {
                return ResourceManager.GetString("Label_EmployNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Number is required.
        /// </summary>
        public static string Label_EmployNumber_Required {
            get {
                return ResourceManager.GetString("Label_EmployNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string Label_Extension_Employee {
            get {
                return ResourceManager.GetString("Label_Extension_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension is required.
        /// </summary>
        public static string Label_Extension_Employee_Required {
            get {
                return ResourceManager.GetString("Label_Extension_Employee_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Label_FirstName {
            get {
                return ResourceManager.GetString("Label_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Label_FirstName_Employee {
            get {
                return ResourceManager.GetString("Label_FirstName_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is required.
        /// </summary>
        public static string Label_FirstName_Employee_Required {
            get {
                return ResourceManager.GetString("Label_FirstName_Employee_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Description.
        /// </summary>
        public static string Label_FormInDescription {
            get {
                return ResourceManager.GetString("Label_FormInDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form  Name.
        /// </summary>
        public static string Label_FormInfoName {
            get {
                return ResourceManager.GetString("Label_FormInfoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Label_GeneralCreate {
            get {
                return ResourceManager.GetString("Label_GeneralCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Label_GeneralDelete {
            get {
                return ResourceManager.GetString("Label_GeneralDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Label_GeneralEdit {
            get {
                return ResourceManager.GetString("Label_GeneralEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Label_Index {
            get {
                return ResourceManager.GetString("Label_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string Label_JobTitle_Employee {
            get {
                return ResourceManager.GetString("Label_JobTitle_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title is required.
        /// </summary>
        public static string Label_JobTitle_Employee_Required {
            get {
                return ResourceManager.GetString("Label_JobTitle_Employee_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobTitle Description.
        /// </summary>
        public static string Label_JobTitleDescription {
            get {
                return ResourceManager.GetString("Label_JobTitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobTitle.
        /// </summary>
        public static string Label_JobTitleName {
            get {
                return ResourceManager.GetString("Label_JobTitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Label_LastName_Employee {
            get {
                return ResourceManager.GetString("Label_LastName_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is required.
        /// </summary>
        public static string Label_LastName_Employee_Required {
            get {
                return ResourceManager.GetString("Label_LastName_Employee_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Label_MasterCountry {
            get {
                return ResourceManager.GetString("Label_MasterCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Management.
        /// </summary>
        public static string Label_MasterEmployee {
            get {
                return ResourceManager.GetString("Label_MasterEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Access.
        /// </summary>
        public static string Label_MasterFormAccess {
            get {
                return ResourceManager.GetString("Label_MasterFormAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Info.
        /// </summary>
        public static string Label_MasterFormInfo {
            get {
                return ResourceManager.GetString("Label_MasterFormInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Label_MasterLanguage {
            get {
                return ResourceManager.GetString("Label_MasterLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Label_MasterRole {
            get {
                return ResourceManager.GetString("Label_MasterRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States.
        /// </summary>
        public static string Label_MasterState {
            get {
                return ResourceManager.GetString("Label_MasterState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Label_MasterSubCity {
            get {
                return ResourceManager.GetString("Label_MasterSubCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Label_MasterSubCountry {
            get {
                return ResourceManager.GetString("Label_MasterSubCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Label_MasterSubemployee {
            get {
                return ResourceManager.GetString("Label_MasterSubemployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Titles.
        /// </summary>
        public static string Label_MasterSubJobTitles {
            get {
                return ResourceManager.GetString("Label_MasterSubJobTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offices.
        /// </summary>
        public static string Label_MasterSubOffices {
            get {
                return ResourceManager.GetString("Label_MasterSubOffices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Label_MasterUser {
            get {
                return ResourceManager.GetString("Label_MasterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string Label_MasterUserManagement {
            get {
                return ResourceManager.GetString("Label_MasterUserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office City.
        /// </summary>
        public static string Label_OfficeCity {
            get {
                return ResourceManager.GetString("Label_OfficeCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Code.
        /// </summary>
        public static string Label_OfficeCode {
            get {
                return ResourceManager.GetString("Label_OfficeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Country.
        /// </summary>
        public static string Label_OfficeCountry {
            get {
                return ResourceManager.GetString("Label_OfficeCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        public static string Label_OfficeId_Employee {
            get {
                return ResourceManager.GetString("Label_OfficeId_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office is required.
        /// </summary>
        public static string Label_OfficeId_Employee_Required {
            get {
                return ResourceManager.GetString("Label_OfficeId_Employee_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office phone.
        /// </summary>
        public static string Label_Officephone {
            get {
                return ResourceManager.GetString("Label_Officephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Postal Code.
        /// </summary>
        public static string Label_OfficePostalCode {
            get {
                return ResourceManager.GetString("Label_OfficePostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office State.
        /// </summary>
        public static string Label_OfficeState {
            get {
                return ResourceManager.GetString("Label_OfficeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string Label_Password_error {
            get {
                return ResourceManager.GetString("Label_Password_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string Label_Read {
            get {
                return ResourceManager.GetString("Label_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports to.
        /// </summary>
        public static string Label_ReportsTo_Employee {
            get {
                return ResourceManager.GetString("Label_ReportsTo_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Label_ReportsTo_Employee_Required {
            get {
                return ResourceManager.GetString("Label_ReportsTo_Employee_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Label_RoleDescription {
            get {
                return ResourceManager.GetString("Label_RoleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string Label_RoleName {
            get {
                return ResourceManager.GetString("Label_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Label_Search {
            get {
                return ResourceManager.GetString("Label_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Here To Search.
        /// </summary>
        public static string Label_SearchToolTip {
            get {
                return ResourceManager.GetString("Label_SearchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Name.
        /// </summary>
        public static string Label_SecondName {
            get {
                return ResourceManager.GetString("Label_SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Name is required.
        /// </summary>
        public static string Label_State_Name_Required {
            get {
                return ResourceManager.GetString("Label_State_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string Label_StateName {
            get {
                return ResourceManager.GetString("Label_StateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supermarket.
        /// </summary>
        public static string Label_SuperMarket {
            get {
                return ResourceManager.GetString("Label_SuperMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Label_Url {
            get {
                return ResourceManager.GetString("Label_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string Label_UserName {
            get {
                return ResourceManager.GetString("Label_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All FormAccess.
        /// </summary>
        public static string lst_AllFormAccess {
            get {
                return ResourceManager.GetString("lst_AllFormAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Roles.
        /// </summary>
        public static string lst_AllRoles {
            get {
                return ResourceManager.GetString("lst_AllRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Users.
        /// </summary>
        public static string lst_AllUsers {
            get {
                return ResourceManager.GetString("lst_AllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Users.
        /// </summary>
        public static string lst_RoleUser {
            get {
                return ResourceManager.GetString("lst_RoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Roles.
        /// </summary>
        public static string lst_UserRole {
            get {
                return ResourceManager.GetString("lst_UserRole", resourceCulture);
            }
        }
    }
}
